services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symphony-api
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
      - mongo
      - postgres
    networks:
      - symphony-network
    env_file:
      - .env

  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    ports:
      - "7474"
      - "7687"
    networks:
      - symphony-network


  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017"
    networks:
      - symphony-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432"
    networks:
      - symphony-network

networks:
  symphony-network:
    driver: bridge
