version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symphony-api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
    env_file:
      - .env
