name: Go

on:
  push:
    branches: [ "**" ]
    paths:
      - '**/*.go'
      - '.golangci.yml'
  pull_request:
    branches: [ "**" ]
    paths:
      - '**/*.go'
      - '.golangci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Download Go modules
      run: |
        go mod tidy
        go mod download

    - name: Generate Swagger Docs
      run: go install github.com/swaggo/swag/cmd/swag@latest && swag init -g cmd/api/main.go -o tmp/docs

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v8.0.0

    - name: Hadolint Github Action
      uses: jbergstroem/hadolint-gh-action@v1.12.2

    - name: Build Application
      run: go build -v ./...